
"""add theme column to users and update message_attachments.updated_at

Revision ID: d78a2b2ec8ee
Revises: bbba8c5e7d65
Create Date: 2026-03-03 09:59:18.656093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd78a2b2ec8ee'
down_revision: Union[str, None] = 'bbba8c5e7d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('theme', sa.String(length=20), nullable=True))
    
    userrole_enum = postgresql.ENUM('ADMIN', 'USER', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=userrole_enum,
               existing_nullable=False,
               postgresql_using='role::text::userrole')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    userrole_enum = postgresql.ENUM('ADMIN', 'USER', name='userrole')
    
    op.alter_column('users', 'role',
               existing_type=userrole_enum,
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    
    userrole_enum.drop(op.get_bind(), checkfirst=True)
    
    op.drop_column('users', 'theme')
    op.alter_column('message_attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
