
"""add system_prompt to conversation

Revision ID: d432b2cc3690
Revises: b6bb3c84ee2d
Create Date: 2026-01-07 11:10:32.641922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd432b2cc3690'
down_revision: Union[str, None] = 'b6bb3c84ee2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'system_prompt')
    # ### end Alembic commands ###
